# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 01304c5c9dcc69fa9b74e1c118e3600d763cd391fbff8ead35bbf871af75f711b6957f081e822eb6129e06caface8069073fe04c929e509048c33664830e418f

test:
  secret_key_base: 4a8c80f95be45554c175bc0465836442b49bcd4787787e392e58adfc6e78eb6277a79706831a4cf9448b4a96bbe25efb1a0a1950c15431fe971d1d0569d0e913

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
